@baseAddress = http://localhost:5105

GET {{baseAddress}}/api/categories
Accept: application/json

###
POST {{baseAddress}}/api/categories
Accept: application/json
Content-Type : application/json
{
  "name":"Category 1"
}
###
